# SPDX-License-Identifier: MIT

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync -p 3.12

      - name: lint
        run: uv run ruff check .

      - name: format
        run: uv run ruff format --check .
